//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisticsWebApplication.StatisticsServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistics", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Statistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameLoseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrawField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GameWon {
            get {
                return this.GameWonField;
            }
            set {
                if ((object.ReferenceEquals(this.GameWonField, value) != true)) {
                    this.GameWonField = value;
                    this.RaisePropertyChanged("GameWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GameLose {
            get {
                return this.GameLoseField;
            }
            set {
                if ((object.ReferenceEquals(this.GameLoseField, value) != true)) {
                    this.GameLoseField = value;
                    this.RaisePropertyChanged("GameLose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Draw {
            get {
                return this.DrawField;
            }
            set {
                if ((object.ReferenceEquals(this.DrawField, value) != true)) {
                    this.DrawField = value;
                    this.RaisePropertyChanged("Draw");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisticsServiceRef.StatisticsServiceSoap")]
    public interface StatisticsServiceSoap {
        
        // CODEGEN: Generating message contract since element name f from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        StatisticsWebApplication.StatisticsServiceRef.UploadFileResponse UploadFile(StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.UploadFileResponse> UploadFileAsync(StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name GetStatisticsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatistics", ReplyAction="*")]
        StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponse GetStatistics(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponse> GetStatisticsAsync(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatisticsJSON", ReplyAction="*")]
        StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponse GetStatisticsJSON(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatisticsJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponse> GetStatisticsJSONAsync(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatisticsXML", ReplyAction="*")]
        StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponse GetStatisticsXML(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatisticsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponse> GetStatisticsXMLAsync(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(StatisticsWebApplication.StatisticsServiceRef.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] f, string fileName) {
            this.f = f;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(StatisticsWebApplication.StatisticsServiceRef.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UploadFileResponseBody {
        
        public UploadFileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatistics", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequestBody Body;
        
        public GetStatisticsRequest() {
        }
        
        public GetStatisticsRequest(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStatisticsRequestBody {
        
        public GetStatisticsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponseBody Body;
        
        public GetStatisticsResponse() {
        }
        
        public GetStatisticsResponse(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<StatisticsWebApplication.StatisticsServiceRef.Statistics> GetStatisticsResult;
        
        public GetStatisticsResponseBody() {
        }
        
        public GetStatisticsResponseBody(System.Collections.Generic.List<StatisticsWebApplication.StatisticsServiceRef.Statistics> GetStatisticsResult) {
            this.GetStatisticsResult = GetStatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsJSON", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequestBody Body;
        
        public GetStatisticsJSONRequest() {
        }
        
        public GetStatisticsJSONRequest(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatisticsJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public GetStatisticsJSONRequestBody() {
        }
        
        public GetStatisticsJSONRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponseBody Body;
        
        public GetStatisticsJSONResponse() {
        }
        
        public GetStatisticsJSONResponse(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatisticsJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatisticsJSONResult;
        
        public GetStatisticsJSONResponseBody() {
        }
        
        public GetStatisticsJSONResponseBody(string GetStatisticsJSONResult) {
            this.GetStatisticsJSONResult = GetStatisticsJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsXML", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequestBody Body;
        
        public GetStatisticsXMLRequest() {
        }
        
        public GetStatisticsXMLRequest(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatisticsXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public GetStatisticsXMLRequestBody() {
        }
        
        public GetStatisticsXMLRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponseBody Body;
        
        public GetStatisticsXMLResponse() {
        }
        
        public GetStatisticsXMLResponse(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatisticsXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatisticsXMLResult;
        
        public GetStatisticsXMLResponseBody() {
        }
        
        public GetStatisticsXMLResponseBody(string GetStatisticsXMLResult) {
            this.GetStatisticsXMLResult = GetStatisticsXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatisticsServiceSoapChannel : StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticsServiceSoapClient : System.ServiceModel.ClientBase<StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap>, StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap {
        
        public StatisticsServiceSoapClient() {
        }
        
        public StatisticsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatisticsWebApplication.StatisticsServiceRef.UploadFileResponse StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.UploadFile(StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(byte[] f, string fileName) {
            StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.UploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            StatisticsWebApplication.StatisticsServiceRef.UploadFileResponse retVal = ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.UploadFileResponse> StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.UploadFileAsync(StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.UploadFileResponse> UploadFileAsync(byte[] f, string fileName) {
            StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.UploadFileRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.UploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            return ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponse StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.GetStatistics(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest request) {
            return base.Channel.GetStatistics(request);
        }
        
        public System.Collections.Generic.List<StatisticsWebApplication.StatisticsServiceRef.Statistics> GetStatistics() {
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequestBody();
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponse retVal = ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).GetStatistics(inValue);
            return retVal.Body.GetStatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponse> StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.GetStatisticsAsync(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest request) {
            return base.Channel.GetStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsResponse> GetStatisticsAsync() {
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsRequestBody();
            return ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).GetStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponse StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.GetStatisticsJSON(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest request) {
            return base.Channel.GetStatisticsJSON(request);
        }
        
        public string GetStatisticsJSON(string no) {
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequestBody();
            inValue.Body.no = no;
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponse retVal = ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).GetStatisticsJSON(inValue);
            return retVal.Body.GetStatisticsJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponse> StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.GetStatisticsJSONAsync(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest request) {
            return base.Channel.GetStatisticsJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONResponse> GetStatisticsJSONAsync(string no) {
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsJSONRequestBody();
            inValue.Body.no = no;
            return ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).GetStatisticsJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponse StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.GetStatisticsXML(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest request) {
            return base.Channel.GetStatisticsXML(request);
        }
        
        public string GetStatisticsXML(string no) {
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequestBody();
            inValue.Body.no = no;
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponse retVal = ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).GetStatisticsXML(inValue);
            return retVal.Body.GetStatisticsXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponse> StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap.GetStatisticsXMLAsync(StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest request) {
            return base.Channel.GetStatisticsXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLResponse> GetStatisticsXMLAsync(string no) {
            StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest inValue = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequest();
            inValue.Body = new StatisticsWebApplication.StatisticsServiceRef.GetStatisticsXMLRequestBody();
            inValue.Body.no = no;
            return ((StatisticsWebApplication.StatisticsServiceRef.StatisticsServiceSoap)(this)).GetStatisticsXMLAsync(inValue);
        }
    }
}
